---
- hosts: all
  become: true
  tasks:

  - name: updating indexes
    apt: 
        update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    apt:
      name: apache2
